server:
  port: 8081

spring:
  main:
    banner-mode: off
  application:
    name: fraud-service
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'

#management:
#  tracing:
#    sampling:
#      probability: 1.0

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
