CREATE TABLE IF NOT EXISTS fraud_check_history
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    update_date  TIMESTAMP WITHOUT TIME ZONE,
    create_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    customer_id  BIGINT,
    is_fraudster BOOLEAN,
    CONSTRAINT pk_fraud_check_history PRIMARY KEY (id)
);
